import usersSlice from '../slices/usersSlices'

export const {
  getAllUsersRequest,
  getAllUsersSuccess,
  getAllUsersFailure,
  registrationRequest,
  registrationSuccess,
  registrationFailure,
  logoutUser,
  loginUserRequest,
  loginUserSuccess,
  loginUserFailure,
  deleteUserRequest,
  deleteUserSuccess,
  deleteUserFailure,
  banUnbanRequest,
  banUnbanSuccess,
  banUnbanFailure,
  checkUserTaskRequest,
  checkUserTaskSuccess,
  checkUserTaskFailure,
  verifyUserRequest,
  verifyUserSuccess,
  verifyUserFailure,
  forgotPasswordRequest,
  forgotPasswordSuccess,
  forgotPasswordFailure,
  resetPasswordRequest,
  resetPasswordSuccess,
  resetPasswordFailure,
  editRequest,
  editSuccess,
  editFailure,
  passwordRequest,
  passwordSuccess,
  passwordFailure,
  updateUserContentStatusRequest,
  updateUserContentStatusSuccess,
  updateUserContentStatusFailure,
  checkUserPassedCourseRequest,
  checkUserPassedCourseSuccess,
  checkUserPassedCourseFailure,
} = usersSlice.actions
